name: Deploy to AWS S3
description: 'Deploy a static web site to AWS S3'
inputs:
  bucket: 
    descrition: 'AWS bucket name'
    required: true
  bucket-region:
    description: 'AWS region for the bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder to be deployed'
    required: true
outputs:
  website-url:
    description: 'URL of the deployed site'
runs:
  using: 'node16'
  main: 'main.js'