name: Lint, test and delpoy a project
on: 
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - main
  push:
    branches:
      - main
      - 'dev-*' # dev-new (with * / is not allowed)
      - 'feature/**' # feature/11/new, feature/11 (** means we can have / there)
    paths-ignore: 
      - '.github/workflows/*' # will trigger pipeline only if there are other changes then workflow changes
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code (as we do not have it by defult)
        uses: actions/checkout@v3
      - name: Install Node (not mandatory as ubuntu has it preinstalled, but let's install more modern version)
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get the code (as we do not have it by defult)
        uses: actions/checkout@v3
      - name: Install Node (not mandatory as ubuntu has it preinstalled, but let's install more modern version)
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-js: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output content
        run: ls
      - name: Output JS filename
        run: echo "${{ needs.build.outputs.script-js }}"
      - name: Deploy
        run: echo "Deploying..."   
